### ISSUE TITLE
Change arcolinux-logout into archlinux-logout

### ISSUE THREAD

**Issue by arcolinuxz** [etrigan63/kittycafe-dm#1]
Could you please change all references of arcolinux-logout into archlinux-logout?
![ArcoLinux-2022-07-01_19-15](https://user-images.githubusercontent.com/36679406/176940690-1e1f307c-4b64-4499-a941-7335ba487f35.png)

**Comment by etrigan63** [comment]
fixed and updated.
[image: photo]
Carlos Echenique
Photographer at  CE Photographic
P  305.219.2433  <305.219.2433>
E  ***@***.***  ***@***.***>
W  cephotographic.com  <http://cephotographic.com>
<http://instagram.com/cephotographic> <http://facebook.com/cephotos>
<http://www.flickr.com/photos/echenique>

"Behind every great man is a woman rolling her eyes." - Jim Carrey.
Create your own email signature
<https://www.wisestamp.com/create-own-email-signature/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>
